### ISSUE TITLE
Use system cache directories for cache and wheelhouse

### ISSUE THREAD

**Issue by juliankrause** [Yelp/pip-faster#23]
There is a standard under Linux for where to store per user caches of data http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html. It would be good if venv-update used these directories instead of ~/.pip

There are similar standards also for Mac OS X which would also be good to use.

**Comment by bukzor** [comment]
This will happen naturally when we finally get to pip6+  (#27).

As such, this isn't really a separate action item.
