### ISSUE TITLE
why not use optparse or argparse instead of the custom parseargs?

### ISSUE THREAD

**Issue by NorthIsUp** [Yelp/pip-faster#43]
If there is no compelling reason I'll refactor parseargs away in favor of a builtin solution.

pytnon2.6 was mentioned so probably optparse.

**Comment by bukzor** [comment]
Yes, I need python2.6 support, so argparse is out.

optparse doesn't help with positional arguments (that's the main improvement in argparse), which is the tricky bit imo.

Feel free to try though. If it's simpler and passes tests, I'll take it.

**Comment by bukzor** [comment]
To answer the question directly, it was simple enough to write it this way, and satisfies all my requirements, so I didn't think about it twice.
