### ISSUE TITLE
"remove from the cache and wheelhouse that have not been accessed in a week" destroys wheels we still want

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/pip-faster#79]
I think the intent of this change was to remove old packages which are no longer needed (e.g. packages which are updated every day).

However, it's making some of our runs *much* slower. If I build a virtualenv with venv_update, then run venv_update again a week later, it will be a no-op, but wipe out my wheel cache since I haven't used those wheels (since the packages were already installed). Then if I run venv_update again, it will rebuild all the wheels.

```bash
ckuehl@supernova:~/ocf-proj/ocfweb$ cd $(mktemp -d)
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ echo ocflib > requirements.txt
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ cp ~/proj/pip-faster/{pip_faster.py,venv_update.py} .
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ python3.4 venv_update.py -ppython3.4
> /usr/bin/python3.4 -m virtualenv virtualenv_run -ppython3.4
[...]
Building wheels for collected packages: ocflib,colorama,cracklib,dnspython3,pexpect,pycrypto,pyyaml,redis,sqlalchemy,ply
  Running setup.py bdist_wheel for ocflib
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for colorama
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for cracklib
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for dnspython3
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for pexpect
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for pycrypto
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for pyyaml
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for redis
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for sqlalchemy
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for ply
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
[...]
Successfully installed ocflib pysnmp requests dnspython3 pyyaml cracklib redis colorama pycrypto pexpect ldap3 paramiko sqlalchemy pymysql pyasn1 pysmi ecdsa ply
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ du -hs ~/.pip/wheelhouse
3.7M    /home/c/ck/ckuehl/.pip/wheelhouse
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ find ~/.pip/wheelhouse -type f -exec touch -a --date='10 days ago' {} \;
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ python3.4 venv_update.py -ppython3.4
Keeping virtualenv from previous run.
[...]
Requirement already up-to-date: ocflib in ./virtualenv_run/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Cleaning up...
> find /home/c/ck/ckuehl/.pip/cache /home/c/ck/ckuehl/.pip/wheelhouse -not -atime -7 -delete
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ du -hs ~/.pip/wheelhouse
4.0K    /home/c/ck/ckuehl/.pip/wheelhouse
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ python3.4 venv_update.py -ppython3.4
> /usr/bin/python3.4 -m virtualenv virtualenv_run -ppython3.4
[...]
Building wheels for collected packages: ocflib,colorama,cracklib,dnspython3,pexpect,pycrypto,pyyaml,redis,sqlalchemy,ply
  Running setup.py bdist_wheel for ocflib
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for colorama
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for cracklib
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for dnspython3
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for pexpect
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for pycrypto
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for pyyaml
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for redis
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for sqlalchemy
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
  Running setup.py bdist_wheel for ply
  Destination directory: /home/c/ck/ckuehl/.pip/wheelhouse
[...]
Successfully installed ocflib pysnmp requests dnspython3 pyyaml cracklib redis colorama pycrypto pexpect ldap3 paramiko sqlalchemy pymysql pyasn1 pysmi ecdsa ply
ckuehl@supernova:/tmp/tmp.T2CbjVYkZK$ du -hs ~/.pip/wheelhouse
3.7M    /home/c/ck/ckuehl/.pip/wheelhouse
```

**Comment by chriskuehl** [comment]
@ENuge

**Comment by ENuge** [comment]
Hmm, I didn't think it would happen often that the wheels wouldn't be touched for a week. But that's assuming pip's check modifies the access time, and if that check happens the average build would be more frequent than once a week. Seems like at least one of those is wrong here. 

Let me know if this is urgent--I'll look more into it when I'm back in office on Thursday. My first thought on alternatives:
1. only delete old packages/wheels if a newer version of said package/wheel exists (I'd want to confirm that packages/wheels follow a name/version convention so that's possible).
2. just always only delete the package that this change was intended for (our translations package). Hacky, would have to be hardcoded somewhere outside of this github project.
3. change the -atime to 2 weeks or something? (would make this happen half as often...but not really a solution).

**Comment by bukzor** [comment]
@ENuge The core issue is that the wheel isn't accessed, the atime isn't updated, when the package is already installed, so people that go for more than a week without doing a clean rebuild will feel the pain when that time comes.

**Comment by chriskuehl** [comment]
One option is to touch all wheels that would have been used to rebuild the virtualenv every time we run venv-update, even if we don't need to use any of them. This helps the problem, especially if you work consistently on the same projects (and never go more than a week without touching a project). This was my plan of attack.

It still feels yucky to wipe people's wheels, though -- disk space is cheap, time spent waiting isn't. There's lots of precedent for leaving files like this around and providing a command to clean up (e.g. apt-get, and even newer versions of pip). I wonder if there's any other way we can address the need to remove old wheels.

**Comment by bukzor** [comment]
@chriskuehl the concern is our localization package, it bumps multiple times per day and is quite large.

**Comment by chriskuehl** [comment]
@bukzor I know, it just feels like a rare case. I understand why it matters to us, but in most cases it's functionality the average person wouldn't want at all. Especially after we upgrade to pip >= 6, if we carry over this feature, we might be killing wheels that the user didn't even install via venv-update (which could be really annoying).

I don't know of a better solution.

**Comment by chriskuehl** [comment]
This line was deleted in bbeb55eded2ff5867377c887d293ab4890d9b643 so we can close this issue.

Do we need to open another issue now that we're not deleting old wheels?

**Comment by asottile** [comment]
Yes I think so
