### ISSUE TITLE
Can we use the same wheel store as pip?

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/pip-faster#81]
[pip >= 7 builds and caches wheels](https://mail.python.org/pipermail/distutils-sig/2015-May/026474.html), similar to what we do. Can we store wheels we build in the same location to share the work?

On my machine it prints lines like:
```
Running setup.py bdist_wheel for numpy
Stored in directory: /home/c/ck/ckuehl/.cache/pip/wheels/b3/d0/9c/c860a697e3ea6929e396a5c55fc5aa2ed7413d24332a9c5299
```

for reference, here's what that directory looks like: https://gist.github.com/anonymous/9e746e749735f7d49d76

**Comment by bukzor** [comment]
This will happen naturally when we port pip-faster to pip>=6.

This is slated in #27
